version: '3.7'

services:
  mysql:
    image: mysql
    container_name: mysqlServer
    restart: always
    volumes:
      - mysql-server:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_DATABASE: users_db
    ports:
      - '3306:3306'

volumes:
  mysql-server:
# POSTGRES
# version: '3'

# services:
#   database:
#     image: 'postgres:latest'
#     container_name: postgresServer
#     restart: always
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: user1234
#       POSTGRES_DB: myDB
#   volumes:
#     - db-data:/var/lib/postgresql/data/

# volumes:
#   db-data: